---
Name: headlesspdf
---
ATWX\HeadlessPDF\Services\HeadlessPDFService:
  chrome_binary: '/usr/bin/chromium-browser'
  chrome_args:
    - '--headless'
    - '--disable-gpu'
    - '--no-sandbox'
    - '--disable-dev-shm-usage'
  timeout: 30
